apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: mattermost
    namespace: mattermost
spec:
    chart:
        spec:
            chart: mattermost-team-edition
            reconcileStrategy: ChartVersion
            version: 6.6.21
            sourceRef:
                kind: HelmRepository
                name: mattermost-helm-source
                namespace: flux-system
    interval: 10m0s
    values:
        image:
            repository: mattermost/mattermost-team-edition
            tag: 7.8.9@sha256:e9adf2c7b53f9f59ea5334a389f2819bb24d9296c388972ca3a0155e6dfccb0e
            imagePullPolicy: IfNotPresent
        persistence:
            data:
                enabled: true
                existingClaim: mattermost-mattermost-team-edition
                storageClass: longhorn
                accessMode: ReadWriteOnce
            plugins:
                enabled: true
                existingClaim: mattermost-mattermost-team-edition-plugins
                storageClass: longhorn
                accessMode: ReadWriteOnce
        service:
            type: ClusterIP
            externalPort: 8065
            internalPort: 8065
        ingress:
            enabled: true
            path: /
            annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/proxy-body-size: 50m
                nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
                nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
                nginx.ingress.kubernetes.io/proxy-buffering: "on"
                nginx.ingress.kubernetes.io/configuration-snippet: |
                    proxy_cache mattermost_cache;
                    proxy_cache_revalidate on;
                    proxy_cache_min_uses 2;
                    proxy_cache_use_stale timeout;
                    proxy_cache_lock on;
            hosts:
                - talk.improwised.com
            tls:
                - secretName: talk.improwised.com-tls
                  hosts:
                    - talk.improwised.com
        route:
            enabled: false
        externalDB:
            enabled: true
            externalDriverType: mysql
            externalConnectionString: ENC[AES256_GCM,data:U6W7C0nkeW6Xicq6fuQ+E+jiERs9EIeSEZKoedNnB0aJUrTUFvkelA6xrU8KGgs8AKVnzb0Od3BplkjFsCog+UJO/ZxTcHKmE2TjhNvlmZ0NFdgvnggTELzrgHjQxnzSE+sWeDmvH7GXvyUmO7e/Fg==,iv:LjAwiL6DQA8GeZq8XAcJW+kMnyaF7rY1t4XYho79Ieo=,tag:K4ruZesNwOkyX02PaQC8pw==,type:str]
        mysql:
            enabled: false
        securityContext:
            fsGroup: 2000
            runAsGroup: 2000
            runAsUser: 2000
        config:
            MM_PLUGINSETTINGS_CLIENTDIRECTORY: ./client/plugins
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://10.43.104.142:8200
          engine_path: transit
          key_name: RBAC
          created_at: "2023-09-12T09:09:17Z"
          enc: vault:v1:Zkty79bXpddXIZwC+tn4bmj6wzWRCYiM3OWY2PQ0ohP4J/ZkdvM7yu9Fhf6GWGLlnfqaqs5gWJEqG48B
    age: []
    lastmodified: "2023-09-12T09:09:17Z"
    mac: ENC[AES256_GCM,data:Ux66za/DOrV6TLv3Do72aUjvUDQwOsxNLKseF2lVYaDbi9seUXgLrpMDzRTm/+GDy3dQoyxJhDvqAna/6dmzsUA8CFJz2UveeMI0i1gSc5NpGUWZ6sNdWZFuntRYd1LSLsiL/sBoksTHUl4p51Y81Ao62ZeTW9TGgPD3rD8+FNw=,iv:Otsmm1e081Kg7XzFM6zakjYfbbZFBnZ5vxzeKpF6Ch8=,tag:kJIZqGdENLMt0O+1P3YKeQ==,type:str]
    pgp: []
    encrypted_regex: ^(externalConnectionString)$
    version: 3.8.0-rc.1
