apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: mattermost
    namespace: mattermost
spec:
    chart:
        spec:
            chart: mattermost-team-edition
            reconcileStrategy: ChartVersion
            version: 6.6.21
            sourceRef:
                kind: HelmRepository
                name: mattermost-helm-source
                namespace: flux-system
    interval: 10m0s
    values:
        image:
            repository: mattermost/mattermost-team-edition
            tag: 7.8.9@sha256:e9adf2c7b53f9f59ea5334a389f2819bb24d9296c388972ca3a0155e6dfccb0e
            imagePullPolicy: IfNotPresent
        persistence:
            data:
                enabled: true
                storageClass: longhorn
                accessMode: ReadWriteOnce
            plugins:
                enabled: true
                storageClass: longhorn
                accessMode: ReadWriteOnce
        service:
            type: ClusterIP
            externalPort: 8065
            internalPort: 8065
        ingress:
            enabled: true
            path: /
            annotations:
                kubernetes.io/ingress.class: nginx
                cert-manager.io/cluster-issuer: letsencrypt-prod
                nginx.ingress.kubernetes.io/proxy-body-size: 50m
                nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
                nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
                nginx.ingress.kubernetes.io/proxy-buffering: "on"
                nginx.ingress.kubernetes.io/configuration-snippet: |
                    proxy_cache mattermost_cache;
                    proxy_cache_revalidate on;
                    proxy_cache_min_uses 2;
                    proxy_cache_use_stale timeout;
                    proxy_cache_lock on;
            hosts:
                - talk.improwised.com
            tls:
                - secretName: talk.improwised.com-tls
                  hosts:
                    - talk.improwised.com
        route:
            enabled: false
        externalDB:
            enabled: true
            externalDriverType: mysql
            externalConnectionString: ENC[AES256_GCM,data:jzH13+o6bWuKTgl9E8HEeQ7TOBKx3kUa2Es3WgFjdHEVUL1XN+1QZtV0xbXU9yrfMR0ynyqxqewSZ7MfuD3fUxg84FA3RYqmhiwhFsAZFSrsmLoHjkbfQlEt6QypOSc6/yEc2AFFRMPLJid4O9tDXQ==,iv:Oowz1kOYiQ2EpVg69ob+ziQlx0915TofswvBZuAF9A4=,tag:SXzNBg/Xyh6N05Z8q1R1ow==,type:str]
        mysql:
            enabled: false
        securityContext:
            fsGroup: 2000
            runAsGroup: 2000
            runAsUser: 2000
        config:
            MM_PLUGINSETTINGS_CLIENTDIRECTORY: ./client/plugins
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://10.43.104.142:8200
          engine_path: transit
          key_name: RBAC
          created_at: "2023-09-12T09:30:43Z"
          enc: vault:v1:U7ZVk2YzyIXM5daZfqIaZVYMTJ6Z26fsgIx3ci3Ni5NsNYmid/Ub1aZpoqcQt2IFYa/HqWduuLTmgvaj
    age: []
    lastmodified: "2023-09-12T09:30:43Z"
    mac: ENC[AES256_GCM,data:JFHKweAcJK0PS/hFSHlniPCeRBRXm/QgH0w/lVOqqJkUJeMp8sYs+bSc7BdM1Fb8Rim9Efq8t9xm4+sKczUJawU8T2DlDDGOOvPJxOdJxhl5eUDwe9OioHxk9WEvH6TFJW3rb1OeeLqSODbVp+XmrgFPvMqlQeWuY9/Dq8KbDU8=,iv:PLpgqULfGifpY28DkBty0TdaQFpCIoO6/KDdbbRwyVc=,tag:BUdgTgCzSvsJNG5DkFT6Bg==,type:str]
    pgp: []
    encrypted_regex: ^(externalConnectionString)$
    version: 3.8.0-rc.1
