apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: temporal
  namespace: temporal
spec:
  repo: https://armory.jfrog.io/artifactory/charts/
  chart: temporal
  targetNamespace: temporal
  timeout: 1000s
  valuesContent: |-
    server:
      metrics:
        annotations:
          enabled: false    
      config:   
        persistence:
          default:
            cassandra:
              hosts:
                - "temporal-cassandra"
              port: "9042"
              user: "cassandra"
              existingSecret: "temporal"
          visibility:
            cassandra:
              hosts:
                - "temporal-cassandra"
              port: "9042"
              user: "cassandra"
              existingSecret: "temporal"
    schema:
      setup:
        enabled: true
      update:
        enabled: true
    elasticsearch:
      enabled: false
    prometheus:
      enabled: false
    grafana:
      enabled: false
    cassandra:
      enabled: true
      persistence:
        enabled: true
        storageClass: longhorn
        resources:
          limits:
            cpu: 1200m
      config:
        cluster_size: 1
