apiVersion: v1
stringData:
    mysecret: ENC[AES256_GCM,data:I7Pg0IYn6A0iP78t8i0=,iv:W1JxJuHh4Xk+SwmjMxEm+RL8+EVcPWXg8DnzeNAP2ec=,tag:kNnk1TbIEo6ZfF50KsaWwg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: demo
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://10.43.104.142:8200
          engine_path: sops
          key_name: firstkey
          created_at: "2023-09-06T10:45:10Z"
          enc: vault:v1:miqggkq3tWv0WXlVjrG/ES9UJmUJ9eTsQwkSR07CCl34t0ttXeB33WquvP82vvSztdnFKaCMSKNUgXnOOssOSwLYfCTK+oMkvzQoHSZT7e151mT+fXKRv830mU+tL7ur+oQJCB8FWnJ8JxXh+JBBMEPanFXvWDOQaOkd18Kq8mhKkY8CDmHIpFkyaPzRNSNaNfOfO/vzT1Yzd750W5wyvRDPpyHYKDLw6vC+IAkCO1//IOkLcw74albpLwGD6zuyYTriXfKsADH+S4Lrw/qV3xhSXEsO70ArQAvglyi5ZDVZPc9lxWmzQgL7ZAD0x6BWwm2fkVqikEzENsDNU7pbzC+9sLteXSVP2ywp8uhFSyxZMi7E6307VpD3QaZ6FS3MImytHvZWFTIUAnI+NNfVDbTV3mogjMgswxXiezZCExSw7ODAC4Qa/Eh5rCERHUPLk0EcFGW1qYnLK5igZtcik1oHxhipsl5FWkNoLnECSh5q8d7Tp3OVH3jSVmm4s+KOKQjJ7+ACamdRld4JRt0/64jNefYjxpz5/vJZIUeOYZZSLAdrcuIflKPadhhRk8sDCO5pjysQXDYiSFshnAdfchtgaDSlaxl3Ui3Lj9CPGgdCrIO1MPildIaqtFffP/ukZ1R4fRh7r8GOsXOAotMgwtt91oQs8wqnEeVbc7x0Pjw=
    age: []
    lastmodified: "2023-09-06T10:45:10Z"
    mac: ENC[AES256_GCM,data:Mn1vubl0p/1UtEOlZtxfJfIy3LFzEXGsLmLohgM1elYlrh92asA3zxBx/VJ1Qr1fHL8pqY07mLlsNPwv7mD37zD6O090ad9KYL1pS6YK31CE4GgYF59KSxPp7Qg8w91OIrQB8e8BYIF8PUlMdl/wz4gCaKCZ3zs3hNFU4GUat0I=,iv:UYULArWf/SKUViMLJZrUG+6mmkEMdqVfKUuh/SKqZm4=,tag:HhHfTTZggZFJtbDlHLsRdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0-rc.1
