name: b1 ONLY

on:
  push:
    branches:
      - b1
  workflow_run:
    workflows: ["Deploy Kubernetes sites by merging the main branch into the kubernetes branch"]
    types:
      - completed

env:
  SOURCE_BRANCH: "${{ github.event.pull_request.head.ref }}"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      timeout-minutes: 5
