name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  SOURCE_BRANCH: "${{ github.event.pull_request.head.ref }}"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      timeout-minutes: 5

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      timeout-minutes: 5

    - name: Create Tag
      id: tag
      run: echo "tag=${{ github.ref_name }}-$(git rev-parse --short HEAD)-$(date +%s)" >> $GITHUB_OUTPUT
      timeout-minutes: 5

    - name: Login to OCIR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.OCI_REGISTRY }}  # Registry region
        username: ${{ secrets.OCI_USERNAME }}  #<tenancy>/<username>
        password: ${{ secrets.OCI_TOKEN }}  # Auth Token
      timeout-minutes: 5


    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.OCI_REGISTRY }}/axeegc0fjto8/backoffice:${{ steps.tag.outputs.tag }}
      timeout-minutes: 5
